# Generated by Django 2.1 on 2018-09-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='num_awards',
        ),
    ]
