# Generated by Django 2.1 on 2018-09-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_publisher_num_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
