# Generated by Django 2.1 on 2018-09-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20180910_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
